# Generated by Django 3.1.7 on 2021-08-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
